# Generated by Django 4.2.3 on 2023-08-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_pledge_supporter_alter_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sport',
            field=models.TextField(default='no_sport_selected'),
        ),
    ]
